name: 'Python test'
description: 'description'

runs:
  using: "composite"
  steps:
    - name: PR Check
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "pull request check from nested action"
      shell: bash