name: 'check-git-semi-linear'
description: 'check-git-semi-linear'
    
runs:
  using: "composite"
  steps:
    - name: Check semi-linear history
      run: |
        echo "Checking semi-linear history"

      shell: bash