name: 'Python test'
description: 'description'
inputs:
  github-pat:
    description: 'github persoanl access token'
    required: true
  test-variable:
    description: 'Initial test variable'
    required: true
# test
runs:
  using: "composite"
  steps:      
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-pat }}
        fetch-depth: 0 # Fetch entire git history

    - name: Checkout Code in common Github Actions Repository
      uses: actions/checkout@v3
      with:
        repository: twattley/test-actions-remote
        token: ${{ inputs.github-pat }}
        path: test-actions-remote

    - name: login echo
      uses: twattley/test-actions-remote/main-folder/echo-push-text@main

    - name: read file
      uses: twattley/test-actions-remote/main-folder/read-from-file@main
      with:
        test-variable: ${{ inputs.test-variable }}

    - name: read file
      uses: twattley/test-actions-remote/main-folder/echo-pr-text@main



