name: 'Python test'
description: 'description'
inputs:
  github-pat:
    description: 'github persoanl access token'
    required: true
  test-variable:
    description: 'Initial test variable'
    required: true


runs:
  using: "composite"
  steps:
    - name: Check Repository
      if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@v3
      with:
        github-pat: ${{ inputs.github-pat }}

    - name: Check Common Actions Repository
      if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@v3
      with:
        repository: twattley/test-actions-remote
        github-pat: ${{ inputs.github-pat }}
        path: test-actions-remote

    - name: PR Check
      if: ${{ github.event_name == 'push' }}
      run: echo "push check from nested action"
      shell: bash

