name: "Check Git History"
description: "Composition of functions desgined to check the linearity of a git repositories history"

# test
runs:
  using: "composite"
  steps:
    - name: Check-out code
      uses: actions/checkout@v3
      run: |
        echo hello
      shell: bash
