name: 'Python test'
description: 'description'
inputs:
  github-pat:
    description: 'github persoanl access token'
    required: true
  test-variable:
    description: 'Initial test variable'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Check Common Actions Repository
      uses: actions/checkout@v3
      with:
        repository: twattley/test-actions-remote
        token: ${{ inputs.github-pat }}
        path: test-actions-remote
    
    - name: list files
      run: | 
        ls -la
        chmod +x  test-actions-remote/helpers/test.sh
        ./test-actions-remote/helpers/test.sh  ${{ inputs.test-variable }}
      shell: bash
