name: "Check Git History"
description: "Composition of functions desgined to check the linearity of a git repositories history"
inputs:
  github-pat:
    description: 'github persoanl access token'
    required: true
  test-variable:
    description: 'Initial test variable'
    required: true
# test
runs:
  using: "composite"
  steps:
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-pat }}
        fetch-depth: 0 # Fetch entire git history

    - name: Checkout Code in common Github Actions Repository
      uses: actions/checkout@v3
      with:
        repository: twattley/test-actions-remote
        token: ${{ inputs.github-pat }}
        path: test-actions-remote

    - name: Notify PR's based on branch
      if: ${{ github.event_name == 'push' }}
      uses: twattley/test-actions-remote/check_git_history/notify-prs-based-on-branch@main
      with:
        test-variable: ${{ inputs.test-variable }}
      env:
        TEST_VAR: 'hello'

    - name: Check Git Semi Linear
      if: ${{ github.event_name == 'push' }}
      uses: twattley/test-actions-remote/check_git_history/check-git-semi-linear@main

    - name: Check Git Semi Linear for PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: twattley/test-actions-remote/check_git_history/check-git-semi-linear-for-pr@main
